# Parameters to test moment matching in different dimensions
simulation_parameters:
  # Number of dimensions
  n_dim_list: [3, 6, 12, 24, 48]
  # variance scales to simulate
  sigma_list: [0.125, 0.25, 0.5, 1.0]
  # types of covariance structure to simulate
  eigval_list: ['exponential']
  eigvec_list: ['random']
  # number of samples for empirical estimates
  empirical_samples: 10000000
  # Number of simualted distributions to fit for each parameter combination
  n_simulations: 50

fitting_parameters:
  # Number of iterations of each fitting cycle
  n_iter: 80
  # Learning rate
  lr: 0.4
  # lr decay parameters
  lr_decay_period: 5
  lr_gamma: 0.85
  # lr decay each cycle start
  n_cycles: 16
  lr_gamma_cycle: 0.85
  # Optimizer and loss function
  loss_type: 'mse'
