SavingDir:
  resultsDir: '../../results/03_nd_mm_training_test_params/'

SimulationParameters:
  # Number of dimensions
  nDim: 25
  # variance scale to simulate
  varScale: 0.25
  # type of covariance structure to simulate
  covType: 'uncorrelated'
  # number of samples for empirical estimates
  nSamples: 1000000
  # Number of simualted distributions to fit for each parameter combination
  nReps: 20

FittingParameters:
  # Number of iterations of each fitting cycle
  nIter: 200
  # Number of cycles of fitting
  nCycles: 6
  # Learning rate
  lr: 0.3
  # lr decay parameters
  decayIter: 10
  lrGamma: 0.85
  # lr decay each cycle start
  cycleMult: 0.5
  # Optimizer and loss function
  optimizerType: 'NAdam'
  lossType: 'norm'
  covWeight: 3
