SavingDir:
  resultsDir: '../../results/04_nd_moment_matching/'

SimulationParameters:
  # Number of dimensions
  nDimVec: [3, 5, 10, 25, 50, 100]
  # variance scales to simulate
  varScaleVec: [0.0625, 0.25, 1.0]
  # types of covariance structure to simulate
  covTypeVec: ['uncorrelated', 'correlated', 'symmetric']
  # number of samples for empirical estimates
  nSamples: 1000000
  # Number of simualted distributions to fit for each parameter combination
  nReps: 100

FittingParameters:
  # Number of iterations of each fitting cycle
  nIter: 200
  # Number of cycles of fitting
  nCycles: 6
  # Learning rate
  lr: 0.2
  # lr decay parameters
  decayIter: 10
  lrGamma: 0.85
  # lr decay each cycle start
  cycleMult: 0.5
  # Optimizer and loss function
  optimizerType: 'NAdam'
  lossType: 'norm'
  covWeight: 3
